# Generated by Django 5.1.6 on 2025-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('simplex', 'Simplex Method'), ('graphical', 'Graphical Method'), ('transportation', 'Transportation Problem')], max_length=20)),
                ('problem_data', models.JSONField()),
                ('solution', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
