# Generated by Django 5.1.6 on 2025-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizationproblem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Optimization Problem', 'verbose_name_plural': 'Optimization Problems'},
        ),
        migrations.AlterField(
            model_name='optimizationproblem',
            name='method',
            field=models.CharField(choices=[('simplex', 'Simplex Method'), ('graphical', 'Graphical Method'), ('transportation', 'Transportation Problem')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='optimizationproblem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
