# Generated by Django 5.1.6 on 2025-03-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_alter_optimizationproblem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizationproblem',
            options={},
        ),
        migrations.AlterField(
            model_name='optimizationproblem',
            name='method',
            field=models.CharField(choices=[('simplex', 'Simplex Method'), ('graphical', 'Graphical Method'), ('transportation', 'Transportation Problem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='optimizationproblem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
